import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import avatarPic from "../assets/avatar.png";
import AnimatedText from "@/components/AnimatedText";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image src={avatarPic} alt="Avatar" className="w-full h-auto" />
            </div>
            <div className="w-1/2">
              <AnimatedText text="Empowering Businesses with Code and Striking Visual Design." />
              <p>
                Building Exceptional Web Solutions as a Proficient Full-Stack
                Developer. Discover My Portfolio and Educational Articles,
                Highlighting My Mastery in React.js and Web Development.
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
